version: "3"
services:
  mariadb:
    container_name: mariadb
    image: bitnami/mariadb:latest
    
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_PASSWORD=agasprosper31
      - MARIADB_DATABASE=bitnami_wordpress
    volumes:
      - mariadb_data:/bitnami/mariadb
    restart: always

  bitnami_wordpress:
    container_name: bitnami_wordpress
    image: bitnami/wordpress:latest
    ports:
      - "8080:8080"
      - "8443:8443"

    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_PASSWORD=agasprosper31
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress

    depends_on:
      - mariadb
    restart: always
    
    volumes:
      - wordpress_data:/bitnami/wordpress

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
 
    